name: bulma_sass
description: Bulma flexbox CSS framework and its scss components
version: 0.7.5
homepage: https://github.com/indiealexh/dart_bulma_sass
author: Alexander Haslam <alexander.haslam@reincarnadigital.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dev_dependencies:
  sass_builder: ^2.1.3
  build_runner: ^1.0.0
  git: ^1.0.0
  pub_semver: ^1.4.2
