name: bulma_sass
description: Bulma flexbox CSS framework and its scss components
version: 0.6.2+1
homepage: https://github.com/indiealexh/dart_bulma_sass
author: Alexander Haslam <alexander.haslam@reincarnadigital.com>

environment:
  sdk: '>=2.0.0-dev.3.0 <2.0.0'

dependencies:
  font_awesome: ^4.7.0

dev_dependencies:
  build_runner: ^0.7.10+1
  sass_builder: ^1.1.2
